[package]
name = "GPUIApplication"
version = "0.1.0"
edition = "2024"

[dependencies]
# GPUI Bits
gpui = { package = "gpui", git = "https://github.com/gpui-ce/gpui-ce" }
gpui_platform = { git = "https://github.com/gpui-ce/gpui-ce", features = ["font-kit"] }

gpui-component = { git = "https://github.com/longbridge/gpui-component", rev = "277f220" }
gpui-component-assets = { git = "https://github.com/longbridge/gpui-component", rev = "277f220" }
smallvec = "=1.15.2"

# Flashcard Libraries
hyperflash = "0.1.0"

# Other
serde = { version = "1.0.228", features = ["derive"] }
toml = "1.1.2+spec-1.1.0"
facet = "0.46.1"
facet-reflect = "0.46.1"
facet-toml = "0.46.1"

[patch."https://github.com/zed-industries/zed.git"]
gpui = { git = "https://github.com/gpui-ce/gpui-ce" }
