[package]
name = "GPUIApplication"
version = "0.1.0"
edition = "2024"

[dependencies]
gpui = { package = "gpui", git = "https://github.com/gpui-ce/gpui-ce" }
gpui_platform = { git = "https://github.com/gpui-ce/gpui-ce", features = ["font-kit"] }

gpui-component = { git = "https://github.com/longbridge/gpui-component", rev = "277f220" }
gpui-component-assets = { git = "https://github.com/longbridge/gpui-component", rev = "277f220" }
smallvec = "=1.15.2"
hyperflash = "0.1.0"

[patch."https://github.com/zed-industries/zed.git"]
gpui = { git = "https://github.com/gpui-ce/gpui-ce" }
